// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function GetAllIPs():Promise<Array<string>>;

export function GetFiles(arg1:number):Promise<Array<main.FileRecord>>;

export function GetMessages(arg1:string,arg2:number):Promise<Array<main.Message>>;

export function GetServerURL():Promise<string>;

export function Login(arg1:string):Promise<Record<string, any>>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveUploadedFile(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
