// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllIPs() {
  return window['go']['main']['App']['GetAllIPs']();
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveUploadedFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveUploadedFile'](arg1, arg2, arg3);
}
